"""add review

Revision ID: 2e96fad13723
Revises: b08bd2d3dc13
Create Date: 2024-10-04 14:01:13.304711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e96fad13723'
down_revision = 'b08bd2d3dc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###
